### PR TITLE
Handle openvpn requiring sudo and add CI tests

### LINKED ISSUE #4: `sudo openvpn` makes the process not exit properly
This is likely the cause for the fail observed in #1. Something seems to be lingering.

### PR DESCRIPTION
**Pull request by BeethovenKodar**
Closes #4.

### CODE REVIEW

**Comment by BeethovenKodar** [comment]
I added CI tests for both macOS and Ubuntu (the ones that used to run locally only before) and sudo stuff works cleanly now. Though I'm not sure how to run the lint check, it seems stuck.

**Comment by BeethovenKodar** [comment]
@bekelley @nkakouros Why is the lint not working just now? https://github.com/KTH-SSAS/python-openvpn-client/actions/runs/11109014995. Also any of you approve this so this is auto-merged when the checks pass.

**Comment by bekelley** [comment]
hmm, i can't figure out why the linter isn't working here.

I had thought maybe it was something changing in Action permissions/access token API, but I just tested from a branch on the twmn repo and it works there.

I'm not sure what has change locally to this repo..

**Comment by BeethovenKodar** [comment]
I'm thinking this repo has to be added to some settings page in twmn-ci.

**Comment by BeethovenKodar** [comment]
@bekelley I'm pretty sure now after reading some documentation that it can't find `lint.yml` since this repo is public and twmn-ci is private and reusing the linting workflow here would disclose the details of the private `lint.yml`. I could copy the original workflow here for the time being, what do you think? Or, we could skip linting and ensure it's done locally instead, or possibly make the twmn-ci repo public although I don't think this is a great solution.

Also, this PR is ready for merging logic-wise.

**Comment by BeethovenKodar** [comment]
image

**Comment by BeethovenKodar** [comment]
@nkakouros @bekelley ?

**Review by bekelley — APPROVED** [review]

**Pull request merged**
